language: php

php:
    - "5.4"

sudo: false

env:
    - WP_VERSION=4.1.1 WP_TEST_DB_NAME=wordpress_tests WP_TEST_DB_USER=travis

before_script:
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - make wp-install
    - make wp-start

after_script:
    - make wp-stop

script: make test
