language: php

php:
    - "5.5"

sudo: false

env:
    - WP_VERSION=4.1.1 WP_TEST_DB_NAME=wordpress_tests WP_TEST_DB_USER=travis

before_script:
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - make wp-install
    - make wp-start
    - sleep 2

after_script:
    - make wp-stop

script: make test

addons:
    artifacts:
        paths:
            - tests/_output
            - wptest/phantom.log
            - wptest/server.log

notifications:
    slack:
        secure: c8vhEs/7VUE/7/FCeBoWyoX+va5YS8S/afnTY7Hk/gUCAqXR+W3nmEGpfz4uzxFUTwhrynimV/9eyt560Y9BrvkNYLMTeDLgB/Otx5jBkuwthd6x9wcLEEup8NPAOj2/r9G0DFadOwSM76ME+H/5ySZ8L5YDOWyJsWR+BZ/MjlY=
